### ISSUE TITLE
Замечания по User Stories

### ISSUE THREAD

**Issue by nvamelichev** [NanamyYu/discraft#2]
- [x] Первая и вторая истории очень похожи, отличаются только мотивацией пользователя (Discord-аккаунта не жалко/Discord-аккаунт - единственный, который у него есть). Я бы объединил их в одну
- [x] Ни в первой, ни во второй истории не указано, как пользователь поступает при повторных запросах авторизации? Код, который ему отправляют в Discord - одноразовый (на каждую авторизацию мы отправляем ему новый код), что безопаснее, или многоразовый, и его надо пользователю как-то у себя хранить?
- [x] В третьей истории я бы уточнил, и писал не "Пользователь..." а "Владелец или администратор Minecraft-сервера..."
- [x] Про владельца/админа сервера я бы ещё подумал и, возможно, добавил историй. Скорее всего, админ/модератор захочет банить людей вошедших через Discord-аккаунт (будет ли это отличаться от обычного бана? подумайте), и смотреть кто заходил через Discord и получилось ли у них (лог аутентификации) чтобы детектировать атаки и т.д. А ещё такое банальное - кто-то захочет выключить ваш плагин (временно) или удалить его (навсегда), это тоже пользовательская история, кажется (как минимум, если ваш плагин где-то будет хранить персистентное состояние, при удалении он точно должен его стереть, при выключении - не знаю.)

**Comment by NanamyYu** [comment]
Про бан людей через Discord-аккаунты мы пока решили не делать, возможно это в каких-нибудь поздних обновлениях плагина появится

**Comment by nvamelichev** [comment]
В целом здесь всё норм , принимается :+1:
